version: '2'

services:
  plodindo:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    volumes:
      - ./bot/:/bot/
      - ./connection/:/bot/connection/
    ports:
      - 5005:5005
    depends_on:
      - actions

  actions:
    build:
      context: .
      dockerfile: ./docker/actions/Dockerfile
    ports:
      - 5055:5055
