version: '2'

services:
  bot:
    build:
      context: .
      dockerfile: ./docker/bot/bot.Dockerfile
    volumes:
      - ./bot/:/bot/
      - ./connections/:/connections/
    ports:
      - 5005:5005
    depends_on:
      - actions

  actions:
    build:
      context: .
      dockerfile: ./docker/actions/actions.Dockerfile
    ports:
      - 5055:5055
    voluems:
      - ./bot/actions/:/bot/actions
